Implement futures market details and trading history on left sidebar
Kwenta/kwenta pull request #1048
Opened 2022-06-24 08:13 UTC by Xiaolei-Shawn

## Description

- Add `FuturesMarketTabs` as container for `TradesHistoryTable` and `FuturesMarketTab`
- Implement `FuturesMarketTab`
- Add `activeTabState` in store for sake of persisting tab state when switching market
- Update `Table` to accept customized row/cell/header props so that the content of cell/header in specific column can be aligned to right.
- Adjust `TradesHistoryTable`
  - Center middle column
  - Align right most column to right

## Related issue

[Issue](https://github.com/Kwenta/kwenta/issues/978)

## Motivation and Context

The reason to extend `Table` component is only styling the child component in table won't affect flex of `TableRow/TableCell/TableHeader`. Extending `Table` to support customization seems to be only solution IMO. I am open for other solution too.

## How Has This Been Tested?

## Screenshots (if appropriate):
![Left sidebar](https://user-images.githubusercontent.com/3646680/175492036-cf5cb117-5c6e-4a9b-8606-037fc972e998.gif)

2022-06-25 10:47 UTC, platschi approved these changes
Deployed version works as intended, well done!

2022-06-25 21:00 UTC, LeifuChen reviewed
@Xiaolei-Shawn The solution looks fine with me.

I think another possible solution is overwriting the css rule by css selector directly.
e.g. in `TradesHistoryTable.tsx`, add something like below
```css
const TableAlignment = css`
	justify-content: space-between;
	& >div:first-child {
		flex: 60 60 0 !important;
	}
	& >div:nth-child(2) {
		flex: 100 100 0 !important;
		display: flex;
		justify-content: center;
	}
	& >div:last-child {
		flex: 70 70 0 !important;
		justify-content: flex-end;
		padding-right: 20px;
	}
`;

const StyledTable = styled(Table)<{ mobile?: boolean }>`
        ....
	.table-row {
		${TableAlignment}
	}
	.table-body-row {
		${TableAlignment}
		padding: 0;
	}
`;
```
Here is the table layout after the css change.
![image](https://user-images.githubusercontent.com/4819006/175790367-7a8ba872-a797-4dc4-bdf6-348cd5d65167.png)

2022-06-26 15:25 UTC, Xiaolei-Shawn commented
> @Xiaolei-Shawn The solution looks fine with me.
> 
> I think another possible solution is overwriting the css rule by css selector directly. e.g. in `TradesHistoryTable.tsx`, add something like below
> 
> ```css
> const TableAlignment = css`
> 	justify-content: space-between;
> 	& >div:first-child {
> 		flex: 60 60 0 !important;
> 	}
> 	& >div:nth-child(2) {
> 		flex: 100 100 0 !important;
> 		display: flex;
> 		justify-content: center;
> 	}
> 	& >div:last-child {
> 		flex: 70 70 0 !important;
> 		justify-content: flex-end;
> 		padding-right: 20px;
> 	}
> `;
> 
> const StyledTable = styled(Table)<{ mobile?: boolean }>`
>         ....
> 	.table-row {
> 		${TableAlignment}
> 	}
> 	.table-body-row {
> 		${TableAlignment}
> 		padding: 0;
> 	}
> `;
> ```
> 

@LeifuChen, I like your solution. TBH, if asking me extending `Table` is kinda overkill and I suppose there is an easy way to solve it. In case we're able to style the component without passing custom style to table, it's recommended to do so. One thing I dislike is `!important` which can be error-prone and working implicitly since it's kinda difficult to predict impacts of `important`. In other hand, adding custom row/header/cell props in `Table` component may not be used commonly given that `Styled` is always preferable (like I mentioned before). I can update it to use css selector if we're not considering `!important` a bad practice.

2022-06-27 06:41 UTC, Xiaolei-Shawn commented
@LeifuChen, I think using `styled` is less invasive so let's go with that. Have pushed the change to align with your comment.

2022-06-27 08:47 UTC, LeifuChen requested changes
@Xiaolei-Shawn Great stuff. Only request a small change on the `NO_VALUE` placeholder. Thanks.

2022-06-27 10:05 UTC, Xiaolei-Shawn commented on sections/futures/FuturesMarketTabs/constants.ts
> +export const DEFAULT_DATA = [
Good catch!

2022-06-27 12:20 UTC, LeifuChen approved these changes
@Xiaolei-Shawn Approved. Thanks for your contribution.

2022-06-27 20:12 UTC, platschi approved these changes
Great work!

2022-06-27 20:12 UTC, merged