fix: localstorage for last market
Kwenta/kwenta pull request #1059
Opened 2022-06-29 02:05 UTC by KngZhi

## Description

Fix last market in localstorage

## Related issue

issue #1057

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-06-30 15:35 UTC, platschi submitted a review, later dismissed
Tested PR deploy and works as expected :+1:

2022-06-30 17:47 UTC, LeifuChen commented
@KngZhi good catch about the weird string. I think the root cause is here https://github.com/Kwenta/kwenta/blob/dev/sections/futures/Trade/MarketsDropdown.tsx#L155
After that, you may also change the code here https://github.com/Kwenta/kwenta/blob/dev/sections/shared/Layout/AppLayout/Header/Nav/Nav.tsx#L30

Thanks for your help.

2022-06-30 17:52 UTC, LeifuChen requested changes

2022-06-30 17:52 UTC, LeifuChen commented on sections/futures/FuturesMarketTabs/FuturesMarketTab.tsx
> +					const asset = `/market/${row.original.asset}`;
After you fixing the issue I mentioned above, we can remove this.

2022-07-01 07:58 UTC, LeifuChen approved these changes
@KngZhi Looks good to me. Thanks for your contributions.

2022-07-01 07:59 UTC, KngZhi commented
Thanks for your guidance! :)

2022-07-01 14:12 UTC, platschi approved these changes
Thank you! Works as requested.

2022-07-01 14:21 UTC, merged