Cross Margin Competition
Kwenta/kwenta pull request #1564
Opened 2022-11-04 19:52 UTC by Tburm

Enable the leaderboard for the upcoming cross margin competition

## Description
* Adds a dropdown to the "Leaderboard" section on the nav
* Adds a competition leaderboard that will pull either round 1 or 2 depending on inputs
* Dynamic tab buttons based on leaderboard type (competition vs all time)
* Opts for a constant instead of an environment variable and recoil value to set competition
  * This shouldn't make any difference, since if we update an environment variable we would still need to redeploy

2022-11-07 15:55 UTC, platschi commented
Do not forget to give the navigation some love ;)

<img width="311" alt="Screenshot 2022-11-07 at 12 54 21" src="https://user-images.githubusercontent.com/548702/200355021-a35ee717-d291-4401-b646-2f90751eabca.png">

2022-11-07 20:06 UTC, platschi requested changes

2022-11-08 12:21 UTC, avclarke approved these changes
Looks good!

2022-11-08 12:24 UTC, platschi approved these changes

2022-11-08 12:24 UTC, merged