Fix input locale issue
Kwenta/kwenta pull request #1889
Opened 2023-01-16 21:14 UTC by koredefashokun

## Description
This PR attempts to fix the locale-related issues with inputs across the Kwenta interface.

## Related issue
#1596 

## Motivation and Context
This ensures that users in European regions do not have issues entering values in the UI.

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):

2023-01-17 08:46 UTC, avclarke approved these changes

2023-01-18 11:11 UTC, platschi requested changes
Unfortunately, this did not change the input. Noticing different behavior between Firefox and Chrome, so browsers might forcefully overwrite the set locale. 

E.g. Firefox displays `5.8995`, while Chrome displays `5,8995` on the deploy for this PR.

Might need to investigate if there's a way to avoid that?

2023-01-20 15:24 UTC, LeifuChen commented
> Unfortunately, this did not change the input. Noticing different behavior between Firefox and Chrome, so browsers might forcefully overwrite the set locale.
> 
> E.g. Firefox displays `5.8995`, while Chrome displays `5,8995` on the deploy for this PR (tested on Exchange)
> 
> Might need to investigate if there's a way to avoid that?

Chrome and Firefox define the locale differently.
- Chrome: by the browser’s language.
- Firefox: by the “lang” attribute (as @koredefashokun did).

We may try sth similar as https://github.com/yairEO/react-number-input

2023-01-23 13:37 UTC, platschi commented
This has been fixed with #1842 by using `text`

2023-01-23 13:37 UTC, closed without merging