chore: display liquadation price
Kwenta/kwenta pull request #1906
Opened 2023-01-24 16:32 UTC by abhisheknaiidu

2023-01-24 17:05 UTC, platschi requested changes

2023-01-24 17:05 UTC, platschi commented on sections/futures/Trade/DelayedOrderConfirmationModal.tsx
> +				label: 'liquidation price',
Please fetch the label from the translations file instead of hardcoding it, see line 113 for reference

2023-01-25 13:40 UTC, Xiaolei-Shawn approved these changes
Looks neat 🚀 . Just a general comment about PR, we would appreciate if dev could provide a basic description/screenshot to pull request (that's why the template is there 😄 ).

2023-01-25 13:50 UTC, platschi commented
> Looks neat 🚀 . Just a general comment about PR, we would appreciate if dev could provide a basic description/screenshot to pull request (that's why the template is there 😄 ).

Agree, when creating a PR Github already provides a template, which should be filled in by developers to make reviews for auditors easier.

2023-01-25 13:51 UTC, platschi approved these changes

2023-01-25 19:32 UTC, merged