chore: deprecate-synths
Kwenta/kwenta pull request #1963
Opened 2023-02-03 19:48 UTC by abhisheknaiidu

## Description
Remove deprecated synths

## Related issue
fixes #1957

## Screenshots (if appropriate):

<img width="498" alt="Screenshot 2023-02-04 at 1 18 09 AM" src="https://user-images.githubusercontent.com/55599878/216694342-f3d64067-27af-4d3b-ad70-26340e848ffa.png">

2023-02-03 20:07 UTC, platschi requested changes
See comments. The dropdown list, when scrolling to the very bottom, also keeps spinning/loading endlessly, it might be related to the github code scanning error (see warning under PR Files in github for https://github.com/Kwenta/kwenta/blob/257b34af1468ca1d7066cc706e62a51cdf9d08ac/sections/shared/modals/SelectCurrencyModal.tsx#L68

![Screenshot 2023-02-03 at 17 06 56](https://user-images.githubusercontent.com/548702/216700855-a500d7dc-7798-4c66-b635-fb6e9ac95bd5.png)

2023-02-03 20:07 UTC, platschi commented on sdk/data/synths.ts
> -			1: '0xbBC455cb4F1B9e4bFC4B73970d360c8f032EfEE6',
We should keep Chainlink on L1 Ethereum (chainID 1) as it seems to be only deprecated on L2 (chainID 10) so far.

2023-02-03 20:07 UTC, platschi commented on sdk/data/synths.ts
> -			1: '0xd2dF355C19471c8bd7D8A3aa27Ff4e26A21b4076',
We should keep Aave on L1 Ethereum (chainID 1) as it seems to be only deprecated on L2 (chainID 10) so far.

2023-02-06 19:11 UTC, LeifuChen commented on sections/shared/modals/SelectCurrencyModal.tsx
>  					{oneInchTokensPaged.length ? (
The infinite loading issue hasn't been fixed. Please check if the length of `oneInchTokensPaged` is different from `oneInchTokenList`.
![image](https://user-images.githubusercontent.com/4819006/217061493-44f54e1a-8fb8-46ed-87bf-040afa7dc1e2.png)

2023-02-06 19:15 UTC, LeifuChen requested changes
Thanks for the work. Please note the following issue:
1. An infinite loader is at the bottom of the select currency modal.
2. All the synths are missing when switching to L1.
3. The category filter is not working.

2023-02-06 20:04 UTC, LeifuChen commented on sections/shared/modals/SelectCurrencyModal.tsx
>  					{oneInchTokensPaged.length ? (
This has been resolved after re-deployment.

2023-02-07 20:25 UTC, platschi approved these changes
Works now on L1 and L2 as requested :+1:

2023-02-08 19:11 UTC, merged