Feat/issue#2046
Kwenta/kwenta pull request #2049
Opened 2023-02-28 15:26 UTC by pldespaigne

- [x] Make submit trade button the color of the trade side
- [x] Make the submit button in the confirmation view the color of the trade side
- [x] Update confirmation submit button labels to include side, e.g. "Submit Short Order"
- [x] Use the colored trade side label in the trade confirmation view
- [x] Update the confirmation view layout

| | |
|-|-|
| ![image](https://user-images.githubusercontent.com/5858657/221897694-5743f73c-8ffe-4402-8557-0c962e3762d3.png) | ![image](https://user-images.githubusercontent.com/5858657/221897778-0352013b-0335-4b36-a334-0abea38451a7.png) |

| | |
|-|-|
| ![image](https://user-images.githubusercontent.com/5858657/221898297-69cc088f-c174-43b0-928f-a83fa51e4ba0.png) | ![image](https://user-images.githubusercontent.com/5858657/221898391-656f42b2-fbfc-487a-8943-772077e36366.png) |

![image](https://user-images.githubusercontent.com/5858657/221898837-35f7434e-c588-4eb5-a10d-7613a3762d38.png)
![image](https://user-images.githubusercontent.com/5858657/221898965-2cb95583-8eea-47fe-9258-2cddabc70951.png)
![image](https://user-images.githubusercontent.com/5858657/221899062-37ca6449-0012-46ca-a793-d3f81ecb95d0.png)

2023-02-28 16:52 UTC, avclarke requested changes
Looking good, just a few minor things.

2023-02-28 16:52 UTC, avclarke commented on sdk/types/futures.ts
> -	| 'Delayed Offchain';
We shouldn't change this underlying type but just make sure we map the naming for user display

2023-02-28 16:52 UTC, avclarke commented on sections/futures/Trade/DelayedOrderConfirmationModal.tsx
> +const Spacer = styled.div`
We have a `Spacer` component you can use

2023-02-28 16:52 UTC, avclarke commented on sections/futures/Trade/ManagePosition.tsx
> +	&.long:hover {
Would be nice if we could add these styles to the base button so we don't have to repeat them in the various places.

2023-02-28 16:52 UTC, avclarke commented on translations/en.json
> +					"tooltip": "Fees are displayed as maker / taker. Maker fees apply to orders that reduce the market skew. Taker fees apply to orders that increase the market skew.",
I think we can just use the existing translations rather than duplicating.

2023-02-28 16:52 UTC, avclarke commented on sections/futures/Trade/DelayedOrderConfirmationModal.tsx
> +const OrderSummaryCell = styled.div`
I think we can use `InfoBoxContainer` and `InfoBoxRow` for these instead of creating new styled components.

2023-02-28 16:52 UTC, avclarke commented on sections/futures/Trade/DelayedOrderConfirmationModal.tsx
> +		() => truncateNumbers(wei(Number(leverageInput) ?? 0), DEFAULT_FIAT_DECIMALS),
We'll probably want to use the calculated leverage in `potentialTradeDetails` here

2023-03-03 13:11 UTC, platschi commented
continued in #2062

2023-03-03 13:11 UTC, closed without merging