gas price summary component update re status l1/l2
Kwenta/kwenta pull request #513
Opened 2022-03-24 17:34 UTC by keybig

the component showing the gas fee text does a Logical OR check on `isMainnet` and `!isCustomGasPrice`  followed by a ternary operation `?:`

```
<SummaryItemLabel>
                {isMainnet || !isCustomGasPrice
                    ? t('exchange.summary-info.max-fee-gwei')
                    : t('exchange.summary-info.gas-price-gwei')}
            </SummaryItemLabel>
```

The reason the text is not updating with L2, is that the !isCustomGasPrice value returns true. This triggers the true ternary ? statement of Max Fee (GWEI).

I have updated the component with a simple ternary using `isL2`, and if true return the specified text, and if false return the specified text.

I have also updated the `en.json` file to change GWEI to Gwei, as requested.

## Related issue
While testing in local, running the ternary with `isMainnet` rather than `isL2` did not trigger the changes in the component necessary. I am not sure why this is, or if it had something to do with my local setup.

## How Has This Been Tested?
Visual testing to confirm the 

## Screenshots (if appropriate):

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/100385397/159975940-96f9fae4-3065-4d45-bd33-fe906664a492.png">

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/100385397/159976105-f1a01e38-3bda-439f-82ae-68e2d5f3dea1.png">

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/100385397/159976278-830a301a-77c9-44c8-b387-3580d5017262.png">

2022-03-25 20:05 UTC, platschi approved these changes

2022-03-28 18:13 UTC, JChiaramonte7 commented
I believe only Mainnet has EIP-1559 and "Max Fee" (cc @brossetti1 ). So we should only show "Max Fee" on mainnet and not other testnets like Kovan.

2022-03-28 18:14 UTC, JChiaramonte7 requested changes

2022-03-28 18:14 UTC, JChiaramonte7 commented on sections/exchange/FooterCard/TradeSummaryCard/GasPriceSummaryItem.tsx
> +				{isL2 ? t('exchange.summary-info.gas-price-gwei') : t('exchange.summary-info.max-fee-gwei')}
Let's only show "Max Fee" on mainnet

2022-03-30 12:50 UTC, platschi approved these changes

2022-03-30 14:55 UTC, JChiaramonte7 approved these changes

2022-03-30 18:15 UTC, merged