Let the position card change when the price moves
Kwenta/kwenta pull request #519
Opened 2022-03-24 20:40 UTC by LeifuChen

## Description
When the price moves, the position card (Position Size, Unrealized P&L, Leverage, Liq) doesn't change automatically. The user has to refresh the page to update the position card.

## Related issue
This is an issue reported by `OP#8194` in `#product-elites` channel
https://discord.com/channels/852273007370960937/953727579582509156/956477422381969438

## Motivation and Context
The position card (Position Size, Unrealized P&L, Leverage, Liq) is supposed to change automatically when the price moves. It will increase the user experience.

## How Has This Been Tested?
1. Open a position and take a screenshot of the position card
2. Wait for the price moves (around 5-10 mins)
3. Compare the position info on dapp with the screenshot taken above

## Screenshots (if appropriate):

2022-03-24 21:18 UTC, platschi commented
Vercel Preview version does not show `PositionCard` data for my open positions.

![Screen Shot 2022-03-24 at 18 17 45](https://user-images.githubusercontent.com/548702/160011856-29a893cd-0623-4cd8-a8b6-a1d121d8f87f.png)

2022-03-24 23:39 UTC, LeifuChen commented
> Vercel Preview version does not show `PositionCard` data for my open positions.
Thanks for testing. The open position issue has been fixed.

2022-03-28 19:04 UTC, Tburm requested changes
My testing did not result in refreshing of positions on price changes. The variable storing the rate does not update, so unless we also update the `marketAssetRate` value when the price updates, the position card will not update.

2022-04-04 21:28 UTC, JChiaramonte7 commented
Yeah this issue can be resolved at the moment. We don't have a mechanism to detect oracle updates at the moment

2022-04-12 12:07 UTC, LeifuChen commented
#666 fixed the reported issue.

2022-04-12 12:07 UTC, closed without merging