fix: removed ETH balance check temporarily.
Kwenta/kwenta pull request #635
Opened 2022-04-07 08:08 UTC by zhyd1997

## Description

## Related issue

Resolves: #626 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-04-07 14:27 UTC, JChiaramonte7 requested changes
Let's also completely strip out the display logic for "no L2 ETH"

2022-04-07 14:27 UTC, JChiaramonte7 commented on sections/exchange/hooks/useExchange.tsx
> +	// const { hasNone: hasNoL2Gas } = L2Gas.useContainer();
Let's not put commented code in the repo. Remove anything we have to remove, we can always revert in the future.

2022-04-07 21:01 UTC, zhyd1997 commented
@JChiaramonte7 Done!

2022-04-08 18:11 UTC, JChiaramonte7 approved these changes

2022-04-08 19:35 UTC, merged