Fix disable input no wallet connection
Kwenta/kwenta pull request #646
Opened 2022-04-08 00:23 UTC by lohba

## Description

Disable the order amount input and withdrawal button when wallet is not connected 
## Related issue

Resolves: #617 
## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-04-11 19:53 UTC, platschi commented
Hey @lohba, almost good to go this ticket, just one last thing, can you remove the `package-lock.json` file from the commit?

2022-04-11 19:55 UTC, platschi requested changes
Hey @lohba, almost good to go this ticket, just one last thing, can you remove the package-lock.json file from the commit?

2022-04-12 12:47 UTC, platschi approved these changes

2022-04-13 11:56 UTC, LeifuChen requested changes
The solution is working well. Just request a minor change to make it more understandable for someone else. Thanks.

2022-04-13 11:56 UTC, LeifuChen commented on sections/futures/Trade/Trade.tsx
> +						!futuresMarketsPosition?.remainingMargin ||
The code will be easier to understand if we use `isWalletConnected` to check the status of the wallet connection. https://github.com/Kwenta/kwenta/blob/v2-dev/store/wallet/index.ts#L35-L37

2022-04-13 16:56 UTC, closed without merging