Improve unsupported network state
Kwenta/kwenta pull request #680
Opened 2022-04-12 22:04 UTC by leovct

## Description
When a user switches to an unsupported network, Kwenta resolves in a white "Unexpected Error" page.

This PR aims to solve this issue by displaying the unsupported wallet state when a user is connected to an unsupported network. This new state consists of the "Switch to L2" CTA button and an "Unsupported Network" button as shown below.

![unsupported-wallet-state](https://user-images.githubusercontent.com/28714795/163061842-f86f5351-f809-463b-bff3-b27a01b6727c.png)

Note: unsupported networks are any other networks than Ethereum, Optimism, Ethereum Kovan and Optimism Kovan.

## Related issue
#557 

## Motivation and Context
This PR solves a bug that was degrading the user experience. The website now behaves properly no matter what chain the user is logged on to. It also makes it clear to the user (in terms of UI/UX) that they are or are not on the right network.

## How Has This Been Tested?
### Test 1
- Connect to the website while already being connected to a supported network with Metamak (i.e. Ethereum or Optimism) and check that the website displays the "Switch to L2" CTA button, the address (or ens name) and the dots button.
- Switch to another supported network, the color or the button updates but the rest of the user menu stays the same.
- Switch to L2, the website displays the "Optimism" button, the address (or ens name) and the dots button.
- Switch to an unsupported network (i.e. Goerli) and check that the website displays the "Switch to L2" CTA button and the "Unsupported Network" button.

### Test 2
- Connect to the website while already being connected to an unsupported network with Metamak (i.e. Goerli) and check that the website displays the "Switch to L2" CTA button and the "Unsupported Network" button.
- Switch to another unsupported network (i.e. Avalanche) and check that the website displays the "Switch to L2" CTA button and the "Unsupported Network" button.
- Switch to L2, the website displays the "Optimism" button, the address (or ens name) and the dots button.
- Switch back to another unsupported network and check again that the website displays the "Switch to L2" CTA button and the "Unsupported Network" button.
- Switch to a supported network (i.e. Ethereum) and check that the website displays the "Switch to L2" CTA button, the address (or ens name) and the dots button.

2022-04-13 18:05 UTC, leovct commented
Yep, it's a typo sorry! I fixed it :)

2022-04-13 22:08 UTC, Tburm requested changes
I found myself in two states that were unexpected...

** Clicking Unsupported Network Button **

1. Connect to a supported network
2. Switch to unsupported network
3. Click "Unsupported Network" button

In this case, it brings up the wallet connection modal. I'm already connected, so I could expect the "switch" and "disconnect' modal, or for the button to do nothing.

** Disconnecting wallet **

1. Connect to a supported network
2. Click wallet button -> disconnect wallet

At this point the button turns into the "Unsupported Network" button. I would expect this to offer the "Connect Wallet" button as if you are disconnected.

2022-04-14 07:31 UTC, leovct commented
Thanks for the review! I fixed both issues. Good catch on the disconnect wallet issue, I missed it. Now, the "Unsupported Network" button does nothing. I tried to make it display the "Switch and Disconnect" modal but the styling was not the same and I didn't want to mess up the WalletActions component.

2022-04-14 19:41 UTC, Tburm approved these changes
Approving the changes, but @platschi maybe we should think about what the actions of the "Unsupported Network" button should be?

2022-04-14 19:59 UTC, merged