Time since oracle update
Kwenta/kwenta pull request #700
Opened 2022-04-15 02:56 UTC by burtrico

Added a tooltip to the futures market price that shows the time since the last oracle update. 

## Description
First I added a tooltip which I made custom in order to cleanly add a timer function to the tooltip component rather than pass down a timer component prop. I also added a query component under queries, useRateUpdateQuery.ts, which queries Synthetix subgraph on optimism-main for the latest "rateUpdate" (oracle price update) which includes a timestamp. Using this query data inside of MarketDetails, I pass the latest oracle price update time to a "TimeTooltip" component that displays the time since the last oracle update using an imported "CountUpTimer" component. 

Currently the timer component only shows the updated time when the tooltip is opened/closed. I can change this to be a live counting timer if desired. 

I also added a styled component hover transform of 1.02 to the market asset perp price. This is very light, but gives the user a slight indication of where the tooltip source is.

## Related issue
[](https://github.com/Kwenta/kwenta/issues/618)

## Motivation and Context
Optimism Oracle price updates are slow. This allows users to have an idea when the last price update came in and then estimate when the next one will be (20min or however long).

## How Has This Been Tested?
I used brave browser, optimism mainnet, and metamask. My changes did not affect other components.

## Screenshots (if appropriate):
<img width="1140" alt="Screen Shot 2022-04-14 at 9 56 15 PM" src="https://user-images.githubusercontent.com/83140889/163510905-92f26a13-d437-40db-bf1b-f5f40cda2e2b.png">

2022-04-21 20:21 UTC, LeifuChen requested changes
@burtrico Good job. Just some small questions about your implementation. Thanks.

2022-04-21 20:21 UTC, LeifuChen commented on components/Tooltip/TimerTooltip.tsx
> +const GeneralTooltip = (props: ToolTipProps) => {
Just curious about why you named this component as `GeneralTooltip` and then put `TimerTooltip` into it.

2022-04-21 20:21 UTC, LeifuChen commented on sections/futures/CountUpTimer/CountUpTimer.tsx
> +			<p>{`Time since oracle update: ${time.minutes}:${time.seconds} min`}</p>
1. Please move this text into `translation\en.json`. 
2. Is the current format by design? Can we show the last update like below in tooltip?

**Last Update**
18 min ago

2022-04-23 17:18 UTC, LeifuChen requested changes
@burtrico Great job! Would you kindly change it to be a liver timer?

2022-04-28 13:19 UTC, LeifuChen requested changes
1. Please clean the code following the lint error.
2. When we move the mouse on both the value of Price and Open Interest, the number is growing bigger. Is this animation by any design?
3. The timer always starts from `23 seconds go` when the prices updates. @Tburm is this from the subgraph?

2022-04-28 13:19 UTC, LeifuChen commented on components/Tooltip/TimerTooltip.tsx
> +			console.log('!! newUpdate =', newUpdate);
Same. Please remove the `console.log`.

2022-04-28 13:19 UTC, LeifuChen commented on components/Tooltip/TimerTooltip.tsx
> +				console.log('useInterval =', totalSeconds);
Please remove the `console.log` before pushing the codes. Thanks.

2022-04-28 13:19 UTC, LeifuChen commented on sections/futures/CountUpTimer/CountUpTimer.tsx
> +			console.log('activeMouse =', activeMouse);
Please remove the `console.log`.

2022-04-28 15:31 UTC, burtrico commented
> 1. Please clean the code following the lint warnings.
> 2. When we move the mouse on both the value of Price and Open Interest, the number is growing bigger. Is this animation by any design?
> 3. The timer always starts from `23 seconds go` when the prices updates. @Tburm is this from the subgraph?



> 1. Lint errors are fixed now
> 2. Yes, I added a slight transform to the two values that have tooltips associated with them. Yashar approved (see below). My thinking is that highlighting/transforming the tooltip source values will clearly show the user what the tooltip is based on and where on the page.
> 3. I'm not sure about the 23 seconds, I'll let you know if I find anything out related to that. If it is consistent then that does seem odd.
<img width="939" alt="Screen Shot 2022-04-28 at 10 20 06 AM" src="https://user-images.githubusercontent.com/83140889/165786802-143d9dce-407e-42e2-b906-42786bfc8bf0.png">

2022-04-28 18:50 UTC, LeifuChen approved these changes
@burtrico Good job! Looks good to me.

2022-04-28 18:51 UTC, merged

2022-04-28 18:52 UTC, LeifuChen commented
@platschi The implementation looks fine. However, the rpc seems not very stable right now. So the oracle timestamp might not be updated in some cases (force refresh will help).