Improve tooltips 874
Kwenta/kwenta pull request #900
Opened 2022-05-26 17:16 UTC by joeyzhaozhao

## Description
Improve tooltips, checking ticket link 
https://github.com/Kwenta/kwenta/issues/874

## Related issue

## Motivation and Context
Improve serval components of tooltips, and remove hovertransferform from code

## How Has This Been Tested?
Check the issue above

## Screenshots (if appropriate):

2022-05-30 19:05 UTC, LeifuChen requested changes
@joeyzhaozhao Thanks for the contribution. Just leave minor comments for your reference.

2022-05-30 19:05 UTC, LeifuChen commented on sections/futures/TradingHistory/SkewInfo.tsx
> +	line-height: 16px;
The numeric value needs to show as `mono` font.

2022-05-30 19:10 UTC, LeifuChen commented on sections/futures/PositionCard/PositionCard.tsx
> +	cursor: help;
As @platschi mentioned, there is no need to include the price with the tooltip cursor.

2022-05-30 21:37 UTC, LeifuChen requested changes
@joeyzhaozhao Just found another tiny thing. As the default font of `tooltip` changed to `regular`, the update of the numeric value will lead to the change of the `TimerTooltip` 's width (which is set to `auto`). Could you please update the font of the numeric value to `mono` again to make sure all the numeric value has the same width? The change is supposed to be made in `TimerTooltip.tsx`. Thanks.
![image](https://user-images.githubusercontent.com/4819006/171060993-018fb172-2630-439e-95dd-637546825699.png)

2022-05-31 19:37 UTC, LeifuChen commented on components/Tooltip/TimerTooltip.tsx
> +import { NumericValue } from 'styles/common';
just remove this unnecessary import.

2022-05-31 20:17 UTC, LeifuChen approved these changes
@joeyzhaozhao Great job!

2022-06-01 09:45 UTC, platschi approved these changes
Great job, looks much better now!

2022-06-01 09:45 UTC, merged